### POST

POST http://localhost:3000/api/signup
content-type: application/json

{
    "userId": 1,
    "username": "wknss",
    "password": "admin123"
}

### GET
GET http://localhost:3000/api/getAll
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6IndrbnNzIiwicGFzc3dvcmQiOiJhZG1pbjEyMyJ9LCJpYXQiOjE2NzMzMDA0ODZ9.FjNeeTXXF0s_c8DIT0p9Tui8yqfCmX0qrNFSPRX8f4s

### GET
GET http://localhost:3000/api/getByName/pikachu
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6IndrbnNzIiwicGFzc3dvcmQiOiJhZG1pbjEyMyJ9LCJpYXQiOjE2NzMzMDA0ODZ9.FjNeeTXXF0s_c8DIT0p9Tui8yqfCmX0qrNFSPRX8f4s

### POST
POST http://localhost:3000/api/post
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6IndrbnNzIiwicGFzc3dvcmQiOiJhZG1pbjEyMyJ9LCJpYXQiOjE2NzMzMDA0ODZ9.FjNeeTXXF0s_c8DIT0p9Tui8yqfCmX0qrNFSPRX8f4s

{
    "name" : "charizard",
    "type" : "fire",
    "generation" : 1,
    "captured" : 1
}


### DELETE
DELETE http://localhost:3000/api/delete/15
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6IndrbnNzIiwicGFzc3dvcmQiOiJhZG1pbjEyMyJ9LCJpYXQiOjE2NzMzMDA0ODZ9.FjNeeTXXF0s_c8DIT0p9Tui8yqfCmX0qrNFSPRX8f4s

### POST
POST http://localhost:3000/api/signin
content-type: application/json

{
    "username": "wknss",
    "password": "admin123"
}

### POST
POST http://localhost:3000/api/edit/3
Content-Type:application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6IndrbnNzIiwicGFzc3dvcmQiOiJhZG1pbjEyMyJ9LCJpYXQiOjE2NzMzMDA0ODZ9.FjNeeTXXF0s_c8DIT0p9Tui8yqfCmX0qrNFSPRX8f4s

{
    "name" : "pikachu",
    "type" : "lightning",
    "generation" : 1,
    "captured" : 1
}